# permissions for end users to edit egeriaservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egeriaserver-editor-role
rules:
- apiGroups:
  - egeria.egeria-project.org
  resources:
  - egeriaservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egeria.egeria-project.org
  resources:
  - egeriaservers/status
  verbs:
  - get
