# permissions for end users to view egeriaplatforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egeriaplatform-viewer-role
rules:
- apiGroups:
  - egeria.egeria-project.org
  resources:
  - egeriaplatforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - egeria.egeria-project.org
  resources:
  - egeriaplatforms/status
  verbs:
  - get
