# permissions for end users to view egeriaservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egeriaserver-viewer-role
rules:
- apiGroups:
  - egeria.egeria-project.org
  resources:
  - egeriaservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - egeria.egeria-project.org
  resources:
  - egeriaservers/status
  verbs:
  - get
