
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - egeria.egeria-project.org
  resources:
  - egeriaplatforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egeria.egeria-project.org
  resources:
  - egeriaplatforms/finalizers
  verbs:
  - update
- apiGroups:
  - egeria.egeria-project.org
  resources:
  - egeriaplatforms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - egeria.egeria-project.org
  resources:
  - egeriaservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egeria.egeria-project.org
  resources:
  - egeriaservers/finalizers
  verbs:
  - update
- apiGroups:
  - egeria.egeria-project.org
  resources:
  - egeriaservers/status
  verbs:
  - get
  - patch
  - update
